sudo: false

language: java

jdk:
- openjdk11

branches:
  only:
  - develop
  - master
  - "/^v[0-9].*/"

cache:
  directories:
  - "$HOME/.m2"

install: true

before_script:
- export TZ=Europe/Berlin

script: mvn clean verify

deploy:
  provider: releases
  api_key:
    secure: NxeUgwrH3eU/nrA+U7ZVWcKPgG0lUTQFQAoMzVyNc69dHPvkQTTUCKI5h8BLkQc8emHrLYTMkZcDyKuXLyvc1j8lFoKhm0W3Mpbpr0wnsJBYixsAo+xwbetVVYAe0+/cM4nIlkMCrpchv3So7flSiJXSOSELg83hs37OZvlRrQuSNQPw2zR2wwuXM7MWBfUlGnwppVoGL0b3bvy5qyTFdYdFDZlKiLtO9W+e1me0TGy9dWCHemEj1+tJWDnBR7zD4mAuXU4f/TYE1djDlxkXib5ysitc7S6kcEcf3nIqslZp+YEJCNuYqrlZdQjofEYU5VmNPj3TB+k5Jxc24SQFOHYupnB8jjPu+tmlLxL26IZkBeZycp7cka3dKROHLmr5Jtxg2aXMArVxMPYQN2DY9JwO4b1Zf7gzbKNEFqGbz8IFHqEtHrTpGowbFNWcCsxyOOVIDaK36oXJZ3tPxM49yqVUMa+JSnDq0xAC1wyQe001qsmaOU22LFW3RnCtWTWQZxHMMD8oz73a7NZJfPmCZ2SlOhJ6d5bNYA2bwq2lDfy19D4KVOAaNwiNn2iQt9S/wB/ufY5PXkxFVcq8TKo4coSVjFrL30FJl46TNSJDA3TuiUf/D2zeqhbxhmdf63z0QyjqIa8DqRHapUuoIl0RLHrfxRENkagSzc/QnrRAAEs=
  file: "./target/bibleserver-scraper-*.jar"
  file_glob: true
  skip_cleanup: true
  on:
    repo: mathisdt/bibleserver-scraper
